export enum Genre {
  ACTION = "Ação",
  ANIMATION = "Animação",
  ADVENTURE = "Aventura",
  COMEDY = "Comédia",
  DOCUMENTARY = "Documentário",
  DRAMA = "Drama",
  ESPIONAGE = "Espionagem",
  FANTASY = "Fantasia",
  WAR_MOVIE = "Filme de Guerra",
  MUSICAL = "Filme Musical",
  NOIR = "Filme Noir",
  GIALLO = "Giallo",
  HISTORICAL = "Histórico",
  HORROR = "Terror",
  CHILDREN = "Infantil",
  MYSTERY = "Mistério",
  ROMANCE = "Romance",
  SUSPENSE = "Suspense",
  THRILLER = "Thriller",
  WESTERN = "Faroeste",
}
